import { logger } from './logger'

/**
 * Word 版本类型（基于 nFib 值检测）。
 */
export type WordVersion =
  | 'word6'      // Word 6.0 (nFib=0x005D=93)
  | 'word95'     // Word 95 / 7.0 (nFib=0x005F=95)
  | 'word97'     // Word 97 / 8.0 (nFib=0x00C1=193)
  | 'word2000'   // Word 2000 / 9.0 (nFib=0x00D9=217)
  | 'word2002'   // Word 2002/XP / 10.0 (nFib=0x00E1=225)
  | 'word2003'   // Word 2003 / 11.0 (nFib=0x0107=263)
  | 'word2007+'  // Word 2007+ (nFib >= 0x0108)
  | 'unknown'

/**
 * 根据 nFib 值检测 Word 版本。
 *
 * nFib 位于 FIB 偏移 2-3（word），标识创建文档的 Word 版本：
 *   - 0x005D (93)  → Word 6.0
 *   - 0x005F (95)  → Word 95 (7.0)
 *   - 0x00C1 (193) → Word 97 (8.0)
 *   - 0x00D9 (217) → Word 2000 (9.0)
 *   - 0x00E1 (225) → Word 2002/XP (10.0)
 *   - 0x0107 (263) → Word 2003 (11.0)
 *   - >= 0x0108    → Word 2007+
 */
export function detectWordVersion(nFib: number): WordVersion {
  if (nFib <= 0x005D) return 'word6'
  if (nFib <= 0x005F) return 'word95'
  if (nFib <= 0x00C1) return 'word97'
  if (nFib <= 0x00D9) return 'word2000'
  if (nFib <= 0x00E1) return 'word2002'
  if (nFib <= 0x0107) return 'word2003'
  if (nFib >= 0x0108) return 'word2007+'
  return 'unknown'
}

/** Word 版本显示名称映射。 */
export const WORD_VERSION_LABELS: Record<WordVersion, string> = {
  word6: 'Word 6.0',
  word95: 'Word 95 (7.0)',
  word97: 'Word 97 (8.0)',
  word2000: 'Word 2000 (9.0)',
  word2002: 'Word 2002/XP (10.0)',
  word2003: 'Word 2003 (11.0)',
  'word2007+': 'Word 2007+',
  unknown: '未知版本',
}

/**
 * Detect whether a WordDocument stream is likely generated by macOS textutil.
 *
 * textutil-generated .doc files have a distinctive FIB signature:
 *   - byte 10 (low byte of fFlags) = 0xBF → fComplex bit is always 1, but encoding is often UTF-16
 *   - minimal FIB structure (cbRgFcLcb is small or zero)
 *   - nFib (word at offset 2) is often atypical
 */
export function isTextutilFib(data: Uint8Array): boolean {
  if (data.length < 32) return false
  // textutil characteristic: byte 10 (fFlags low byte) = 0xBF
  const fFlagsLow = data[10]
  if (fFlagsLow !== 0xBF) return false
  // Minimal / truncated FIB is typical of textutil
  const csw = data[32] | (data[33] << 8)
  if (csw > 100) return false
  return true
}

/** Character counts for each story in the document (FibRgLw rgCcp). */
export interface RgCcp {
  /** Main document body. */
  ccpText: number
  /** Footnotes. */
  ccpFtn: number
  /** Headers and footers. */
  ccpHdd: number
  /** Macro subdocument. */
  ccpMcr: number
  /** Comments (annotations). */
  ccpAtn: number
  /** Endnotes. */
  ccpEdn: number
  /** Text boxes. */
  ccpTxbx: number
  /** Header text boxes. */
  ccpHdrTxbx: number
}

export interface FibData {
  fcClx: number
  lcbClx: number
  fcMin: number
  fcMac: number
  fComplex: boolean
  fibBase: number
  /** True → use 1Table stream; False → use 0Table stream. */
  fWhichTblStm: boolean
  /** True → likely generated by macOS textutil (fComplex unreliable, minimal FIB). */
  isTextutil?: boolean
  /** nFib 值（FIB 偏移 2-3 的 word），用于判断 Word 版本。 */
  nFib?: number
  /** 检测到的 Word 版本（基于 nFib）。 */
  wordVersion?: WordVersion
  /** Per-story character counts from FibRgLw (rgCcp). */
  rgCcp: RgCcp
  /** Offset of PlcfBteChpx in table stream (character properties). */
  fcPlcfBteChpx: number
  /** Length of PlcfBteChpx. */
  lcbPlcfBteChpx: number
  /** Offset of PlcfBtePapx in table stream (paragraph properties). */
  fcPlcfBtePapx: number
  /** Length of PlcfBtePapx. */
  lcbPlcfBtePapx: number
  /** Offset of stylesheet (STTBF) in table stream. */
  fcStshf: number
  /** Length of stylesheet. */
  lcbStshf: number
  /** Offset of font table (STTB Ffn) in table stream. */
  fcSttbfFfn: number
  /** Length of font table. */
  lcbSttbfFfn: number
  /** Offset of List Table (LST) in table stream. */
  fcLst: number
  /** Length of List Table. */
  lcbLst: number
  /** Offset of PlcfLfo in table stream. */
  fcPlcfLfo: number
  /** Length of PlcfLfo. */
  lcbPlcfLfo: number
  /** Offset of PlcfFldMom (field positions in main text) in table stream. */
  fcPlcfFldMom: number
  /** Length of PlcfFldMom. */
  lcbPlcfFldMom: number
  /** Offset of DOP (Document Properties) in table stream. */
  fcDop: number
  /** Length of DOP. */
  lcbDop: number
  /** Offset of SttbfRMark (revision author table) in table stream. Optional — only set when cbRgFcLcb is large enough. */
  fcSttbfRMark?: number
  /** Length of SttbfRMark. */
  lcbSttbfRMark?: number
  /** Offset of PlcfBkf (bookmark starts) in table stream. Optional. */
  fcPlcfBkf?: number
  /** Length of PlcfBkf. */
  lcbPlcfBkf?: number
  /** Offset of PlcfBkl (bookmark ends) in table stream. Optional. */
  fcPlcfBkl?: number
  /** Length of PlcfBkl. */
  lcbPlcfBkl?: number
  /** Offset of SttbfBkmk (bookmark name table) in table stream. Optional. */
  fcSttbfBkmk?: number
  /** Length of SttbfBkmk. */
  lcbSttbfBkmk?: number
  /** Offset of PlcfSed (section descriptor table) in table stream. Optional. */
  fcPlcfSed?: number
  /** Length of PlcfSed. */
  lcbPlcfSed?: number
  /** Offset of PlcfHdd (header/footer position table) in table stream. Optional. */
  fcPlcfHdd?: number
  /** Length of PlcfHdd. */
  lcbPlcfHdd?: number
}

/** Empty rgCcp used for early-return fallbacks. */
const EMPTY_RGCCP: RgCcp = {
  ccpText: 0,
  ccpFtn: 0,
  ccpHdd: 0,
  ccpMcr: 0,
  ccpAtn: 0,
  ccpEdn: 0,
  ccpTxbx: 0,
  ccpHdrTxbx: 0,
}

/**
 * Parse the File Information Block (FIB) from a WordDocument stream.
 *
 * The FIB structure follows the Word 97-2003 binary format:
 *   FibBase (32 bytes) → csw → FibRgW → cslw → FibRgLw → cbRgFcLcb → rgFcLcbBlob
 *
 * Key offsets:
 *   - byte 10 (fFlags word): bit 2 = fComplex (1=8-bit compressed, 0=UTF-16LE)
 *   - byte 11 (fFlags high byte): bit 1 (= word bit 9) = fWhichTblStm
 *   - offset 32: csw (count of FibRgW words)
 *   - offset 34: FibRgW starts (csw+1 words)
 *   - after FibRgW: cslw (4 bytes)
 *   - after cslw: FibRgLw (cslw+1 dwords) — contains cbMac + rgCcp
 *   - after FibRgLw: cbRgFcLcb (2 bytes)
 *   - after cbRgFcLcb: rgFcLcbBlob (pairs of fc/lcb)
 */
export function parseFib(data: Uint8Array): FibData | null {
  if (data.length < 32) {
    logger.warn('数据太短，无法解析FIB')
    return null
  }

  const magic = data[0] | (data[1] << 8)
  if (magic !== 0xa5ec && magic !== 0xa5eb) {
    logger.warn(`无效的FIB magic: 0x${magic.toString(16)}`)
    return null
  }

  logger.log(`FIB magic: 0x${magic.toString(16)}`)

  try {
    // fFlags is a 16-bit field at offset 10.
    //   bit 2 (mask 0x0004): fComplex (1=8-bit compressed, 0=UTF-16LE)
    //   bit 9 (mask 0x0200): fWhichTblStm (1=1Table, 0=0Table)
    const fFlags = data[10] | (data[11] << 8)
    const fComplex = (fFlags & 0x0004) !== 0
    const fWhichTblStm = (fFlags & 0x0200) !== 0
    // Detect macOS textutil-generated files (fComplex flag is unreliable)
    const isTextutil = isTextutilFib(data)
    if (isTextutil) logger.log('检测到 macOS textutil 生成的文件，fComplex 标志可能不可靠')

    // Read nFib (word at offset 2) and detect Word version
    const nFib = data[2] | (data[3] << 8)
    const wordVersion = detectWordVersion(nFib)
    logger.log(`Word 版本: ${WORD_VERSION_LABELS[wordVersion]} (nFib=0x${nFib.toString(16).toUpperCase()})`)

    // csw at offset 32
    const csw = data[32] | (data[33] << 8)

    // FibRgW: csw 16-bit values immediately follow csw (offset 34).
    // Per MS-DOC, csw MUST be 0x0E, so FibRgW97 spans exactly csw * 2 bytes
    // and cslw follows immediately at (34 + csw * 2).
    const fibRgWEnd = 34 + csw * 2
    if (fibRgWEnd + 4 > data.length) {
      logger.warn('FIB FibRgW超出范围，仅使用fFlags标志')
      return {
        fcMin: 0, fcMac: 0, fcClx: 0, lcbClx: 0,
        fComplex, fWhichTblStm, isTextutil, fibBase: 32, rgCcp: { ...EMPTY_RGCCP },
        fcPlcfBteChpx: 0, lcbPlcfBteChpx: 0,
        fcPlcfBtePapx: 0, lcbPlcfBtePapx: 0,
        fcStshf: 0, lcbStshf: 0,
        fcSttbfFfn: 0, lcbSttbfFfn: 0,
        fcLst: 0, lcbLst: 0,
        fcPlcfLfo: 0, lcbPlcfLfo: 0,
        fcPlcfFldMom: 0, lcbPlcfFldMom: 0,
        fcDop: 0, lcbDop: 0,
      }
    }

    // cslw (2-byte count of DWORDs in FibRgLw97) is at fibRgWEnd. FibRgLw97
    // follows immediately with no reserved padding. Per MS-DOC, cslw MUST be
    // 0x16 (22 DWORDs = 88 bytes). Guard against corrupt/non-standard values
    // by falling back to the spec default.
    let cslw = data[fibRgWEnd] | (data[fibRgWEnd + 1] << 8)
    const fibRgLwStart = fibRgWEnd + 2
    if (cslw < 1 || cslw > 200 || fibRgLwStart + cslw * 4 + 2 > data.length) {
      logger.warn(`cslw=${cslw} 非法，回退到默认 22 DWORDs`)
      cslw = 22
    }

    // FibRgLw97 spans cslw DWORDs; cbRgFcLcb follows immediately after.
    const fibRgLwEnd = fibRgLwStart + cslw * 4
    if (fibRgLwEnd + 2 > data.length) {
      logger.warn('FIB FibRgLw超出范围，仅使用fFlags标志')
      return {
        fcMin: 0, fcMac: 0, fcClx: 0, lcbClx: 0,
        fComplex, fWhichTblStm, isTextutil, fibBase: 32, rgCcp: { ...EMPTY_RGCCP },
        fcPlcfBteChpx: 0, lcbPlcfBteChpx: 0,
        fcPlcfBtePapx: 0, lcbPlcfBtePapx: 0,
        fcStshf: 0, lcbStshf: 0,
        fcSttbfFfn: 0, lcbSttbfFfn: 0,
        fcLst: 0, lcbLst: 0,
        fcPlcfLfo: 0, lcbPlcfLfo: 0,
        fcPlcfFldMom: 0, lcbPlcfFldMom: 0,
        fcDop: 0, lcbDop: 0,
      }
    }

    // Parse FibRgLw97's rgCcp values. Layout (relative to fibRgLwStart):
    //   +0  cbMac
    //   +4  reserved1
    //   +8  reserved2
    //   +12 ccpText
    //   +16 ccpFtn
    //   +20 ccpHdd
    //   +24 ccpMcr
    //   +28 ccpAtn
    //   +32 ccpEdn
    //   +36 ccpTxbx
    //   +40 ccpHdrTxbx
    const rgCcpStart = fibRgLwStart
    const rgCcp: RgCcp = {
      ccpText: readDwordAt(data, rgCcpStart + 12),
      ccpFtn: readDwordAt(data, rgCcpStart + 16),
      ccpHdd: readDwordAt(data, rgCcpStart + 20),
      ccpMcr: readDwordAt(data, rgCcpStart + 24),
      ccpAtn: readDwordAt(data, rgCcpStart + 28),
      ccpEdn: readDwordAt(data, rgCcpStart + 32),
      ccpTxbx: readDwordAt(data, rgCcpStart + 36),
      ccpHdrTxbx: readDwordAt(data, rgCcpStart + 40),
    }

    // cbRgFcLcb at fibRgLwEnd (2 bytes word)
    const cbRgFcLcb = data[fibRgLwEnd] | (data[fibRgLwEnd + 1] << 8)

    // rgFcLcbBlob starts after cbRgFcLcb
    const blobStart = fibRgLwEnd + 2
    const blobSize = cbRgFcLcb * 8

    // For libwv/non-standard files, cbRgFcLcb may be invalid (e.g., 0xFFFF)
    // In this case, we still return the parsed rgCcp values for text extraction
    if (blobStart + blobSize > data.length || cbRgFcLcb < 2 || cbRgFcLcb > 1000) {
      logger.warn(`FIB blob无效(cbRgFcLcb=${cbRgFcLcb})，返回rgCcp供文本提取`)
      return {
        fcMin: 0, fcMac: 0, fcClx: 0, lcbClx: 0,
        fComplex, fWhichTblStm, isTextutil, nFib, wordVersion, fibBase: 32, rgCcp,
        fcPlcfBteChpx: 0, lcbPlcfBteChpx: 0,
        fcPlcfBtePapx: 0, lcbPlcfBtePapx: 0,
        fcStshf: 0, lcbStshf: 0,
        fcSttbfFfn: 0, lcbSttbfFfn: 0,
        fcLst: 0, lcbLst: 0,
        fcPlcfLfo: 0, lcbPlcfLfo: 0,
        fcPlcfFldMom: 0, lcbPlcfFldMom: 0,
        fcDop: 0, lcbDop: 0,
      }
    }

    // FibRgFcLcb97 is a fixed-order array of (fc, lcb) pairs, each 8 bytes
    // (4-byte file offset + 4-byte length). cbRgFcLcb is the count of pairs.
    // Field order is defined by MS-DOC §2.5.5. fc values are masked with
    // 0x3FFFFFFF because the top 2 bits act as flags in some fields.
    const fcAt = (pair: number): number =>
      pair < cbRgFcLcb ? readDwordAt(data, blobStart + pair * 8) & 0x3FFFFFFF : 0
    const lcbAt = (pair: number): number =>
      pair < cbRgFcLcb ? readDwordAt(data, blobStart + pair * 8 + 4) : 0

    // fcMin/fcMac are legacy Word 6/95 fields and are NOT part of FibRgFcLcb97.
    // Word 97+ locates text via the piece table (Clx), so these stay 0.
    const fcMin = 0
    const fcMac = 0

    // Pair indices per MS-DOC §2.5.5 FibRgFcLcb97 (matches Apache POI
    // FIBFieldHandler constants):
    const fcStshf = fcAt(1)
    const lcbStshf = lcbAt(1)
    const fcPlcfSed = fcAt(6)
    const lcbPlcfSed = lcbAt(6)
    const fcPlcfHdd = fcAt(11)
    const lcbPlcfHdd = lcbAt(11)
    const fcPlcfBteChpx = fcAt(12)
    const lcbPlcfBteChpx = lcbAt(12)
    const fcPlcfBtePapx = fcAt(13)
    const lcbPlcfBtePapx = lcbAt(13)
    const fcSttbfFfn = fcAt(15)
    const lcbSttbfFfn = lcbAt(15)
    const fcPlcfFldMom = fcAt(16)
    const lcbPlcfFldMom = lcbAt(16)
    const fcSttbfBkmk = fcAt(21)
    const lcbSttbfBkmk = lcbAt(21)
    const fcPlcfBkf = fcAt(22)
    const lcbPlcfBkf = lcbAt(22)
    const fcPlcfBkl = fcAt(23)
    const lcbPlcfBkl = lcbAt(23)
    const fcDop = fcAt(31)
    const lcbDop = lcbAt(31)
    const fcClx = fcAt(33)
    const lcbClx = lcbAt(33)
    const fcSttbfRMark = fcAt(51)
    const lcbSttbfRMark = lcbAt(51)
    const fcLst = fcAt(73)
    const lcbLst = lcbAt(73)
    const fcPlcfLfo = fcAt(74)
    const lcbPlcfLfo = lcbAt(74)

    logger.log(
      `nFib=${data[2] | (data[3] << 8)} fComplex=${fComplex} fWhichTblStm=${fWhichTblStm} ` +
      `fcMin=0x${fcMin.toString(16)} fcMac=0x${fcMac.toString(16)}`
    )
    logger.log(
      `fcClx=0x${fcClx.toString(16)} lcbClx=${lcbClx} ` +
      `ccpText=${rgCcp.ccpText} ccpFtn=${rgCcp.ccpFtn} ccpHdd=${rgCcp.ccpHdd} ` +
      `ccpAtn=${rgCcp.ccpAtn} ccpEdn=${rgCcp.ccpEdn}`
    )
    logger.log(
      `fcPlcfBteChpx=0x${fcPlcfBteChpx.toString(16)} lcbPlcfBteChpx=${lcbPlcfBteChpx} ` +
      `fcPlcfBtePapx=0x${fcPlcfBtePapx.toString(16)} lcbPlcfBtePapx=${lcbPlcfBtePapx} ` +
      `fcStshf=0x${fcStshf.toString(16)} lcbStshf=${lcbStshf} ` +
      `fcSttbfFfn=0x${fcSttbfFfn.toString(16)} lcbSttbfFfn=${lcbSttbfFfn} ` +
      `fcLst=0x${fcLst.toString(16)} lcbLst=${lcbLst} ` +
      `fcPlcfLfo=0x${fcPlcfLfo.toString(16)} lcbPlcfLfo=${lcbPlcfLfo} ` +
      `fcPlcfFldMom=0x${fcPlcfFldMom.toString(16)} lcbPlcfFldMom=${lcbPlcfFldMom} ` +
      `fcDop=0x${fcDop.toString(16)} lcbDop=${lcbDop} ` +
      `fcSttbfRMark=0x${fcSttbfRMark.toString(16)} lcbSttbfRMark=${lcbSttbfRMark}`
    )

    return {
      fcClx, lcbClx, fcMin, fcMac, fComplex, fWhichTblStm, isTextutil, nFib, wordVersion, fibBase: 32, rgCcp,
      fcPlcfBteChpx, lcbPlcfBteChpx, fcPlcfBtePapx, lcbPlcfBtePapx,
      fcStshf, lcbStshf, fcSttbfFfn, lcbSttbfFfn,
      fcLst, lcbLst, fcPlcfLfo, lcbPlcfLfo,
      fcPlcfFldMom, lcbPlcfFldMom,
      fcDop, lcbDop,
      fcSttbfRMark, lcbSttbfRMark,
      fcPlcfBkf, lcbPlcfBkf, fcPlcfBkl, lcbPlcfBkl, fcSttbfBkmk, lcbSttbfBkmk,
      fcPlcfSed, lcbPlcfSed,
      fcPlcfHdd, lcbPlcfHdd,
    }
  } catch (error) {
    logger.error(`FIB解析错误: ${error}`)
    return null
  }
}

function readDwordAt(data: Uint8Array, offset: number): number {
  return (data[offset] | (data[offset + 1] << 8) |
          (data[offset + 2] << 16) | (data[offset + 3] << 24)) >>> 0
}
